version: '3'

services:
  pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
      - 6543:6543
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=dbfpc

  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: .
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/home/node/app